---
- name: Install app
  hosts: all
  become: yes
  gather_facts: yes

  tasks:

  - name: Adding user {{ app }} to group vagrant
    user: name={{ app }}
      groups=vagrant
      append=yes
    when: not rails_env == 'production'

  - block:

    - name: stat "/home/{{ app }}/{{ app }}/config/secrets.yml" 
      stat:
        path: "/home/{{ app }}/{{ app }}/config/secrets.yml"
      register: app_secrets_yml

    - name: stat "/vagrant/{{ app }}/app"
      stat:
        path: "/vagrant/{{ app }}/app"
      register: vagrant_app

    - name: gem install rails
      shell: /home/{{ app }}/.rbenv/shims/gem install rails
      register: gem_install_rails
      changed_when: gem_install_rails.stdout is search('Fetching')
      when: rails_env != 'production' and not vagrant_app.stat.exists

    - name: "rails new {{ app }}"
      shell: cd /vagrant && /home/{{ app }}/.rbenv/shims/rails new {{ app }}
      register: rails_new_app
      when: rails_env != 'production' and not vagrant_app.stat.exists


    - name: symlink /vagrant/{{ app }} to /home/{{ app }}/{{ app }}
      file:
        src: /vagrant/{{ app }}
        dest:  /home/{{ app }}/{{ app }}
        state: link
      when: rails_env != 'production' and not app_secrets_yml.stat.exists


    - name: "add config.hosts << \"{{ app }}.{{ app_domain }}\""
      lineinfile:
        path: /home/{{ app }}/{{ app }}/config/application.rb
        insertafter: "config.load_default"
        line: "config.hosts << \"{{ app }}.{{ app_domain }}\"" 
      when: rails_env != 'production'

    - name: configure "/vagrant/{{ app }}" as safe for git
      git_config:
        name: safe.directory
        scope: global
        value: "/vagrant/{{ app }}"
      when: rails_env != 'production' and not app_secrets_yml.stat.exists

    become: yes
    become_user: "{{ app }}"

  - name: add extra apache config to apache
    blockinfile:
      path: "/etc/apache2/sites-available/{{ vhost }}.conf"
      insertafter: "CustomLog"
      block: "{{ lookup('file', 'templates/apache.conf') }}"
    notify: restart apache2
    when: extra_apache_conf

  - name: install python3-passlib
    apt:
      pkg: 
      - python3-passlib

  handlers:
  - name: restart apache2
    systemd:
      state: restarted
      name: apache2
      enabled: yes


- import_playbook: ansible-rails/install_rails_app.yml 

